-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th5 20, 2021 lúc 06:42 PM
-- Phiên bản máy phục vụ: 10.4.17-MariaDB
-- Phiên bản PHP: 8.0.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `thuvienonline`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `sach`
--

CREATE TABLE `sach` (
  `id` int(255) NOT NULL,
  `idsach` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `tensach` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `tacgia` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `theloai` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `noidung` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `img` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `kho` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `sach`
--

INSERT INTO `sach` (`id`, `idsach`, `tensach`, `tacgia`, `theloai`, `noidung`, `img`, `kho`) VALUES
(1, 'a001', 'Huyền Trân Công Chúa', 'Hoàng Quốc Hải', 'Lịch Sử - Chính Trị', '“Huyền Trân Công Chúa” là một trong bốn tập của bộ tiểu thuyết lịch sử nổi tiếng “Bão Táp Triều Trần” của nhà văn Hoàng Quốc Hải.\r\nCâu chuyện xoay quanh cuộc sống của công chúa Huyền Trân, một nàng công chúa vô cùng khác biệt với các công chúa đương thời. Cô gần gũi, chan hòa và đối xử rất tốt với tất cả mọi người. Không chỉ đẹp về tính cách tâm hồn cô còn có nét đẹp kiêu sa của một người con gái đôi mươi.\r\n\r\nThời đó có quy định rằng cấm con trai, con gái lấy người ngoại tộc nhưng để giữ mối duyên hảo giữa hai nước Đại Việt và Chiêm Thành, thượng hoàng Trần Nhân Tông đã hữa sẽ gả công chúa Huyền Trân cho vua Chế Mân. Công chúa là người thấu tình đạt lý, hiểu rõ nỗi phiền muộn của vua cha, công chúa đã thuận theo mối hôn sự mang tính chất chính trị này.\r\n\r\nNhưng văn hóa và ngôn ngữ của hai quốc gia là hoàn toàn khác biệt nên Huyền Trân phải lĩnh hội tất cả trong một thời gian không phải là dài. Thông mih và quốc sắc thiên hương đã khiến cho nhà vua Chế Mân yêu quý và nhanh chóng nàng nhận được sự ân sủng của ngài. Cũng từ đây những mâu thuẫn giữa trốn hậu cung hình thành ngày càng nhiều,...', 'https://docsach24.com/filemanager/data-images/lich-su-chinh-tri/huyen-tran-cong-chua.jpg', 10),
(2, 'a002', 'Nghìn lẻ một ngày', 'François Pétis De La Croix', 'Cổ Tích - Thần Thoại', '“Nghìn lẻ một ngày” là một cuốn tiểu thuyết kinh điển của tác giả François Pétis De La Croix.\r\nChuyện kể về cô công chúa nọ bị mất niềm tin vào đàn ông. Chỉ do sau một cơn ác mộng đâm ra thù hận đàn ông và rất ghét việc đi lấy chồng. Ngày ngày, nhũ mẫu đều đến và kể cô nghe câu chuyện đó chính là phương pháp giúp cô vượt qua cơn ám ảnh với một người khác giới.\r\n\r\nQuả thực những câu chuyện phát huy hiệu nghiệm, bà cố thuyết phục nàng công chúa, trên đời không thiếu những người đàn ông hào hiệp và chung thuỷ, trước sau rồi nàng cũng sẽ gặp được một chàng trai yêu nàng tha thiết, để nàng yêu lại hết lòng, không sợ bị người ấy lừa dối. Chuyện kể từng đoạn, khớp với thời gian hằng công chúa ở trong nhà tắm, và sao cho thật lôi cuốn, dừng lại ở chỗ gay cấn nhất, để những người nghe không bỏ dở chừng. Và bà đã thành công. Sau đợt \"tâm lý trị liệu\" dài suốt một nghìn lẻ một ngày, nàng công chúa đỏng đảnh và tàn nhẫn của chúng ta được giải thoát khỏi cơn trầm uất vô căn cứ, rồi đồng ý kết hôn với chàng hoàng tử trẻ tuổi, đẹp trai nước Ba Tư.', 'https://docsach24.com/filemanager/data-images/co-tich-than-thoai/nghin-le-mot-ngay.jpg', 17),
(3, 'a003', 'Hiệp Cốt Đan Tâm', 'Lương Vũ Sinh', 'Cổ đại, Kiếm Hiệp - Tiên Hiệp', 'Tuổi thơ mỗi người không phải ai cũng được trải qua một quãng thời gian đáng nhớ nhất của mỗi đời người, đôi khi nó khiến người ta ám ảnh khi phải hình dung lại khoảng khoảng thời gian đó.\r\n\r\nTiểu thuyết “Những dải trắng trên nền đen” là điển hình của tấn bi kịch đó, tác phẩm do tác giả nổi tiếng Ruben David Gonzalez Gallego sáng tác dưới dạng tập truyện ngắn. Cũng như chính cuộc đời Ruben đã làm đảo lộn mọi quan niệm thông thường về hạnh phúc. Một người có ất cả vẫn có thể bất hạnh, còn kẻ bị tước bỏ mọi điều lại là người hạnh phúc nhất. Anh đã chứng minh một chân lí giản dị và xưa cũ, rằng con người không chỉ là một mớ cơ bắp và thần kinh, con người có tâm hồn và tâm hồn có thể tồn tại ngoài thể xác ngay cả khi người ta còn sống.\r\n\r\n“Những dải trắng trên nền đen” đã khiến độc giả phải thay đổi quan điểm của mình về những khía cạnh trước đây họ vẫn thường coi là hiển nhiên đã đúng. Những nhân vật thống khổ của Ruben đã làm được điều đó. ', 'https://docsach24.com/filemanager/data-images/kiem-hiep-tien-hiep/hiep-cot-dan-tam.jpg', 0),
(4, 'a004', 'Đàn cầm duyên tơ', 'Khánh Vân', 'Văn Học Việt Nam', '“Đàn cầm duyên tơ” là tiểu thuyết lãng mạn nhẹ nhàng của tác giả Khánh Vân.\r\nCâu chuyện mở đầu bằng cuộc họp gia đình gấp của gia đình An, cô lấy đó làm bất an. Mỗi lần bất ngờ như vậy đều có điều gì chẳng lành và đặc biệt điều đó lại nhắm đến cô. Quả là không sai, cô đã đoán đúng, bữa cơm đang chỉ rất bình thường cho tới khi mọi người được thông báo là dì Năm ở quê bị bệnh. Đó là do một lá thư gửi từ quê ngoại lên. Và mẹ muốn cô về quê, vài tháng, thật sự là một cú sốc quá lớn. Tưởng chuyện chỉ là vụ thi trượt của cô nhưng ai ngờ lại ra đến nông nỗi này.\r\n\r\nTừ trước tới giờ cô chưa từng về quê ngoại, chưa từng gặp mặt bà ngoại. Liệu bà có thích cô không, một đứa con gái chẳng hề the khuân phép? Đúng, cô luôn phá vỡ mọi quy tác trong gia đình. Mẹ muốn cô học Y Nha Khoa và được sự dìu dắt của Vũ, chàng trai đang theo đuổi cô nhưng An đã âm thâm phá hỏng mọi chuyện. Mẹ thích cô để tóc dài và uốn gọn gàng thành từng lọn nhưng cô thấy nó vô cùng khó chịu và cắt ngắn tất cả,... Cô chưa bao giờ dễ thương trong mắt mọi người vậy liệu ở quê nhà, ngoại có thích cô?', 'https://docsach24.com/filemanager/data-images/van-hoc-viet-nam/Dan-cam-duyen-to-Khanh-Van.jpg', 0),
(5, 'a005', 'Nhạc Phi Diễn Nghĩa', 'Khuyết Danh', 'Tiểu Thuyết Trung Quốc', '“Nhạc phi diễn nghĩa” là một tiểu thuyết dài mang tính sử thi vô cùng nổi tiếng, tác phẩm có mặt trên văn đàn đã từ thời nhà Thanh nhưng nội dung lại là về thời nhà Tống cách đây hơn nửa thế kỉ.\r\n\r\nCâu chuyện xoay quanh nhân vật chính là Nhạc Phi, một anh hùng được người Trung Quốc từ thời xưa ra sức sùng bái. Đối lập với hình ảnh anh hùng bất khuất của Nhạc Phi là nhân vật Tần Cối, một đại gian thần bán nước, cầu vinh mà người Trung Hoa vô cùng căm ghét.\r\n\r\nNhạc Phi với tinh thần yêu nước cao cả đã lấy được trái tim của quần chúng nhân dân, thấy vậy vua Cao Tông lấy làm lo ngại cho vị trí ngai vàng hiện tạo của mình nên đã cùng Tần Cối bày mưu hãm  hại Nhạc Phi. Người anh hùng dân tộc vì thế không may đã bị giết hại, không những vậy biết bao nhiêu vị trung thân ái quốc khác cùng phải bỏ mạng.\r\n\r\nCâu chuyện đề cao tinh thần yêu nước của nhân dân Trung Hoa, đồng thời cùng mang tính nhân văn sâu sắc. Từ đó khiến cho độc giả có thể hình dung được chế độ khắc nghiệt của triều đại Trung Quốc thời bấy giờ.', 'https://docsach24.com/filemanager/data-images/tieu-thuyet-trung-quoc/nhac-phi-dien-nghia.jpg', 44),
(6, 'a006', 'Đế thiên đế thích', 'Nguyễn Hiến Lê', 'Hồi Ký - Tuỳ Bút', '“Đế thiên đế thích” là tác phẩm thuộc thể loại du kí của tác giả của tác giả Nguyễn Hiến Lê. Nhân tiện cũng giới thiệu sơ qua về thể loại này, du kí nếu khéo viết thì có thể đẹp như thơ, vui như tiểu thuyết, mà lại ghi chép được thiên nhiên, xã hội, tình cảm một cách trung thực hơn hoặc dồi dào hơn thơ và tiểu thuyết. Vì vậy mà cho tới thế kỷ trước, thể đó rất được trọng ở phương Đông cũng như phương Tây.\r\n\r\n“Đế thiên đế thích” được tác giả hồi tưởng từ những năm chiến tranh, và từ năm 1943 Nguyễn Hiến Lê bắt đầu viết lại, tác phẩm được coi là một cảnh đại quan vào bậc nhất thế giới, cách Sài Gòn không bao xa, mà theo nhiều người được biết thì từ trước tới nay chưa có du khách Việt Nam nào viết về nó cả. Hồi viết tác phẩm này, ông không hề có ý định muốn in ra hay gì cả, chỉ đơn giản ông muốn lưu lại những dòng hồi ký sắp phai nhạt đi. Nhưng khi đất nước thanh bình rồi, để thảo mãn ước muốn của nhiều độc giả, tác phẩm đã được xuất bản.', 'https://docsach24.com/filemanager/data-images/hoi-ky-tuy-but/de-thien-de-thich.jpg', 57),
(7, 'a007', 'Thành-Cát-Tư-Hãn và đế quốc Mông Cổ', 'Thúc Nguyên', 'Lịch Sử - Chính Trị', '“Thành cát tư Hãn và đế quốc Mông Cổ” là một tác phẩm thuộc thể loại sử thi của tác giả Thúc Nguyên.\r\nĐây là một tác phẩm tiêu biểu khái quát lại cuộc đời và những công lao của Thành Cát Tư Hãn thời kì đó. Tác giả đã tinh tế khai thác về ông ở nhiều góc độ khác nhau, trong nhiều sự việc rất đời thường để thấy ông không phải là thần thánh phương nào cả mà cũng chỉ là một con người có trái tim và cảm xúc mà thôi. Ở cương vị một người cha đối với việc truyền ngôi cho các con, Thành Cát Tư Hãn đã thể hiện mình cũng chỉ là một người cha như bao người cha khác, cũng đau lòng khi nhìn con cái mình mâu thuẫn và ân hận khi cả đời đã dồn quá nhiều tâm huyết vào việc mở rộng lãnh thổ mà không dành nhiều thời gian liên kết các thành viên trong gia đình.\r\n\r\nTác giả đi sâu vào các cuộc viễn chinh mà trước đó là việc Thành Cát Tư Hãn đã gây binh lực Mông Cổ Hùng Mạnh như thế nào. Nhờ vào nghệ thuật này mà quân đội Mông Cổ có thể đánh bại các đế quốc khác cho dù sự chênh lệch giữa số quân là rất lớn trong khi phần yếu thế hơn lại thuộc về Mông Cổ.', 'https://docsach24.com/filemanager/data-images/lich-su-chinh-tri/thanh-cat-tu-han-va-de-quoc-mong-co-thuc-nguyen.jpg', 0),
(8, 'a008', 'Oxford thương yêu', 'Dương Thụy', 'Truyên Teen - Tuổi Học Trò', '“Oxford thương yêu” là một tác phẩm tiểu thuyết xuất sắc của tác giả Dương Thụy. Nói đến Dương Thụy là ta lại thấy bóng dáng của một nhà văn đã mang đến cho độc giả nhiều tác phẩm văn học tràn đầy nhiệt huyết, hoài bão và khát vọng của tuổi trẻ. Và nổi tiếng nhất trong số đó là “Oxford thương yêu” được xuất bản lần đầu tiên năm 2007.\r\n\r\nĐây là câu chuyện của Kim một cô gái trẻ người Việt sang bên nước ngoài du học, tất nhiên không thể tránh khỏi những khó khăn như khác biệt văn hóa, khác biệt ngôn ngữ, gía cả đắt đỏ,... nhưng Kim biết chắc rằng cô sẽ được hoàn thiện bản thân khi gắn bó với nơi đây. \r\n\r\nNhững khung cảnh đẹp đẽ cổ kính của thành phố Oxford của được tác giả Dương Thụy miêu tả hết sức chân thực, ở đây Kim sẽ có mối tình với một bạn trai ngoại quốc. Dù khác biệt rất lớn về mọi thứ nhưng từ sâu họ vẫn gắn kết với nhau rất chặt chẽ. Câu truyện hứa hẹn với một kết thức ngọt ngào viên mãn tạo một động lực lớn vô cùng cho những bạn trẻ đang sắp có ý định sang nước ngoài du học.', 'https://docsach24.com/filemanager/data-images/truyen-teen-tuoi-hoc-tro/oxford-thuong-yeu.jpg', 10),
(9, 'a009', 'Xin Chào, Người Thừa Kế', 'Công Tử Diễn', 'Ngược tâm, Sủng, Truyện Ngắn - Ngôn Tình', 'Xin Chào, Người Thừa Kế là cuốn tiểu thuyết thuộc thể loại ngôn tình hiện đại, ngược, ngọt sủng, hào môn thế gia của tác giả Công Tử Diễn. Nhân vật chính: Trang Nại Nại, Tư Chính Đình.\r\n\r\n\"Trên thế giới này, liệu có người nào khiến cho bạn hi sinh tất cả chỉ để yêu người đó cả một thanh xuân\"\r\n\r\nXin Chào, Người Thừa Kế xoay quanh chuyện tình nhiều sóng gió của cặp đôi chính, Tư Chính Đình yêu say đắm Trang Nại Nại, tình cảm sâu nặng là vậy nhưng biến cố xảy ra, Nại Nại chia tay với Chính Đình và cùng mẹ Trang bỏ đi không lời từ biệt. Thực ra Nại Nại là đại tiểu thư nhà họ Cố nhưng khi mới sinh ra mẹ Trang đã bế nhầm cô.\r\n\r\nBiến mất sau 5 năm, Nại Nại với thân phận Cố Khuynh Nhan quay về tìm Chính Đình. Cuộc sống của cô lúc này gặp nhiều khó khăn nên đã nhờ sự giúp đỡ của Tư Chính Đình. Thời gian ở cạnh nhau, hai người quyết định đi đến hôn nhân, nhưng một lần nữa cuộc hôn nhân đi đến bế tắc vì không hiểu nhau. Tưởng như duyên số chỉ đến đây nhưng vì tình cảm của họ đã dành cho nhau là rất sâu đậm, hai người quyết định bỏ hết những khúc mắc để quay lại. Nhưng đâu thể dễ dàng như vậy, những khó khăn lại ập đến...\r\n\r\nTruyện Xin Chào, Người Thừa Kế xoay là một món ăn rất phù hợp với cả các fan truyện ngược lẫn truyện ngọt sủng. Hai yếu tố ngược - sủng kết hợp hài hoà, đan xen trong truyện không bị làm quá nên tạo sự nhẹ nhàng cho câu chuyện. Người đọc sẽ có lúc bật cười vì những tình huống đáng yêu, lúc có thể rơi nước mắt vì sự giằng xé trong tình cảm của hai nhân vật chính.', 'https://docsach24.com/filemanager/data-images/Truy%E1%BB%87n%20Ng%E1%BA%AFn%20-%20Ng%C3%B4n%20T%C3%ACnh/xin-chao-nguoi-thua-ke.jpg', 0),
(10, 'a010', 'Tây Sở Bá Vương Hạng Võ', 'Thường Vạn Sinh', 'Lịch Sử - Chính Trị', 'Tây Sở Bá Vương hay còn được biết tới dưới cái tên Hạng Võ là một nhà chính trị, tướng quân nổi tiếng, người có công lớn trong việc lật đổ nhà Tần. Cuốn sách “Tây Sở Bá Vương Hạng Võ” là một cuốn sách lịch sử viết về cuộc đời và sự nghiệp của Hạng Võ.\r\n\r\nNhững năm trước công nguyên khi Tần vương Doanh Chính vẫn còn nắm quyền cai trị đất nước cũng là thời kỳ mà đứa bé nhà họ Hạng được sinh ra. Đứa bé trai bụ bẫm có tiếng khóc rất vang như báo hiệu sự ra đời và vai trò quan trọng của nó đối với vận mệnh đất nước lúc bấy giờ. Gia đình đặt tên cho nó là Hạng Võ. Thế rồi, đứa trẻ đó lớn lên khỏe mạnh, càng ngày càng thể hiện được sức mạnh và bán lĩnh của mình.\r\n\r\nCha của Hạng Võ mất sớm nên sống với chú là Hạng Lương. Khi còn nhỏ, Hạng Võ có học chữ nhưng không thành. Thế rồi, trước sự thuyết phục của cháu, Hạng Lương đã dạy cháu học võ và binh pháp…\r\n\r\nQua cuốn sách, bạn đọc sẽ biết được nhiều thông tin hữu ích về nhân vật lịch sử Trung Quốc là Hạng Võ, từ đó, mở rộng nguồn kiến thức lịch sử của mình.', 'https://docsach24.com/filemanager/data-images/lich-su-chinh-tri/tay-so-ba-vuong-hang-vo.jpg', 9),
(11, 'a011', 'Chào Buổi Sáng: Ông Xã Cool Ngầu', 'Hoàng Nhã Thần Hi', 'Truyện Ngắn - Ngôn Tình', 'Cố Niệm – cô cảnh sát giản dị một ngày đuổi theo tên trộm lại tình cờ gặp gỡ vị tổng tài mặt liệt Sở Chiêu Dương. Những hành động vô tình của cô thông qua cách hiểu của Sở Chiêu Dương lại bị anh suy diễn thành cô mới gặp đã thích anh mê mệt. Hiểu lần nối tiếp hiểu lầm khiến bao tình huống dở khóc dở cười diễn ra giữa hai người.\r\n\r\nCố Niệm đơn thuần trong trẻo, luôn cảm thấy vinh dự về công việc của mình. Bất chấp sự phản đối của mẹ, cô luôn yêu nghề vì muốn noi gương người cha cảnh sát đã hy sinh vì nhiệm vụ. Sở Chiêu Dương khi bảy tuổi từng bị bắt cóc. Từ đó, đoạn ký ức tối tăm không ánh mặt trời kia trở thành cơn ác mộng luôn bám theo anh. Sự trầm lặng, khép kín dường như đã trở thành thói quen của anh. Thế nhưng từ khi gặp Cố Niệm, anh dường như đã mở lòng chấp nhận sự hiện hữu của cô. Dĩ nhiên, định mệnh không dễ dàng vun đắp cho họ như vậy. Sự xuất hiện của các “tiểu tam” Ngôn Sơ Vi, Trì Dĩ Hằng tưởng chừng là để ngăn cách họ nhưng thực chất lại là cái cớ để Cố Niệm và Sở Chiêu Dương đến gần với nhau hơn, hiểu rõ tình cảm của chính mình hơn. Gia đình Sở Chiêu Dương chuyên nghiên cứu y học. Lần này công ty của anh bị một thế lực đen tối nhằm vào. Cố Niệm là thành viên của đội hình sự, cô nhận nhiệm vụ đến bảo vệ anh.', 'https://docsach24.com/filemanager/data-images/Truy%E1%BB%87n%20Ng%E1%BA%AFn%20-%20Ng%C3%B4n%20T%C3%ACnh/chao-buoi-sang-ong-xa-cool-ngau-full.jpg', 0),
(12, 'a012', 'Con mèo đã sống một triệu lần', 'Sano Yoko', 'Thiếu Nhi- Tuổi Mới Lớn', 'Truyện ngắn “Con mèo đã sống một triệu lần” là câu chuyện thiếu nhi vô cùng nổi tiêng bên Nhật Bản nhưng người ta bảo đây cũng là truyện dành cho người lớn vì cái ý nghĩa tình yêu bao la trong câu truyện khiến mọi người vào mỗi dịp giáng sinh đều mua tặng truyện này cho người mình yêu.\r\n\r\nCâu truyện kể về con mèo đã chết đi và sống lại cả triệu lần và đương nhiên mèo cũng đã từng có cả triệu người chủ khác nhau. Mỗi lần mèo chết đi chủ của mèo đều khóc hết nước mắt nhưng mèo lại chưa bao giờ rơi một giọt nước mắt nào. \r\n\r\nChỉ cho đến khi mèo gặp một cô mèo trắng khác, cô ấy còn chưa từng sống qua một lần. Mèo và cô ấy ở bên và có với nhau những đứa con hết sức là xinh xắn và dễ thương. Mèo yêu mèo trắng lắm. Cả những đứa con nữa, lần đầu tiên mèo dành tình yêu cho người khác mà không phải bản thân mình. Đến một ngày mèo trắng nằm bất động cạnh mình, mèo trắng mất đi, lần đầu tiên mèo khóc nhiều như vậy. Và mèo từ đó cũng không bao sống lại nữa có lẽ bỏi vì mèo đã tìm ra tình yêu đích thực cho đời mình.', 'https://docsach24.com/filemanager/data-images/thieu-nhi-tuoi-moi-lon/con%20meo%20trieu%20kiep.jpg', 5),
(13, 'a013', 'An Nam Chí Lược', 'Lê tắc', 'Lịch Sử - Chính Trị', '“An Nam chí lược” là bộ sách sử thi do Lê Tắc soạn thảo khi đang sống lưu vong ở bên Trung Quốc ở khoảng nửa đầu thế kỉ 14.\r\n\r\nLúc đó, Lê Tắc là là một tên tội đồ phản quốc, trong lúc nước nhà đang gặp ngoại xâm, xã tắc nguy cấp, nhân dân đau khổ, Lê Tắc cùng bọn Trần Kiện và Trần Ích Tắc, không những không chịu gắng sức phấn đấu để cứu nước cứu dân, trái lại nhẫn tâm đầu hàng và làm tôi địch. Hơn nữa trong bộ \"An Nam Chí Lược\", Lê Tắc quên mình là người Việt, dựa vào lập trường và quan điểm người Nguyên để soạn tập.\r\n\r\nNhưng theo nhiều nhà nghiên cứu, tác phẩm mang một giá trị lịch sử rất lớn, là tư liệu quý báu có liên quan đến cổ sử và trung sử của Việt Nam. Nội dung sử của nước nhà có trong tác phẩm rất phong phú đa dạng, đó còn được coi là những cứ liệu thành văn đáng tin cậy, phản ánh một chặng dài lịch sử từ thế kỷ XIV trở về trước.\r\n\r\nĐây được coi là một bộ sử xưa nhất do người Viêt Nam soạn ra, đây thực sự là một bộ sử học thuần túy thiết thực và quý báu cho mọi đối tượng độc giả nghiên cứu.', 'https://docsach24.com/filemanager/data-images/lich-su-chinh-tri/An-Nam-Chi-Luoc.jpg', 0),
(14, 'a014', 'Mẫu Thượng Ngàn', 'Nguyễn Xuân Khánh', 'Văn Hóa - Tôn Giáo', '“Mẫu thượng ngàn” được coi là một tác phẩm đã làm nên bước ngoặt to lớn cho nhà văn Nguyễn Xuân Khánh. Là một người trong thế hệ cầm bút trưởng thành trong cuộc cách mạng, Nguyễn Xuân Khánh đã gây nên một bất ngờ lớn trên văn đàn qua một loạt tiểu thuyết dày dặn mà điển hình là Mẫu thượng ngàn với đề tài viết về văn hóa Việt trong giai đoạn thực dân Pháp xâm lược Việt Nam cuối thế kỉ XIX đầu thế kỉ XX.\r\n\r\n“Mẫu thượng ngàn” nói về những tầng lớp trí thức trưởng thành trong cách mạng đang mang nặng trong mình hệ tư tưởng mới khác  hoàn toàn so vợi hệ giá trị của đạo Khổng. Những tấm gương nghĩa khí của những nhà Nho dân tộc như cụ Cử Khiêm, cụ Vũ Huy Tân là những đại diện xuất sắc nhất thể hiện khí tiết và phẩm chất kiên trung của người trí thức. Tác phẩm tiếp cận với một vấn đề mang tính lịch sử không riêng bất cứ đất nước nào, thời đại nào: vị trí, vai trò xã hội cũng như thái độ của người trí thức trong lịch sử.\r\n\r\n“Mẫu thượng ngàn” như một viên ngọc sáng chiếu vào tâm gương của những người tri thức đi trước để từ đó làm khuân mẫu cho các thế hệ sau này.', 'https://docsach24.com/filemanager/data-images/van-hoc-ton-giao/mau-thuong-ngan1.jpg', 0),
(15, 'a015', 'NAM HOA KINH', 'Trang Tử', 'Triết Học', '“Nam hoa kinh” hay còn được gọi là Nam Hoa Chân Kinh, là một tác phẩm nổi tiếng do Trang Tử sáng tác, Trang Tử là một trong những nhà tư tưởng đặc biệt vào loại hạng nhất thời ấy, rất giỏi kể chuyện, có sức tưởng tượng vô cùng phong phú.\r\n\r\nNội dung của “Nam Hoa Kinh” bao gồm  hơn mười vạn câu để châm biếm cái học của Khổng Từ. Cả tác phẩm được chia ra làm 3 phần: nội thiên, ngoại thiên và tập thiên. Trong đó, nội thiên bao gồm gồm 7 thiên có tựa đề là: Tiêu dao du, Tề vật luận, Dưỡng sinh chủ, Nhân gian thế, Đức sung phù, Đại tôn sư, Ứng đế vương. Ngoại thiên gồm 15 thiên có tựa đề là: Biền mẫu, Mã đề, Khứ cự, Tại hựu, Thiên địa, Thiên đạo, Thiên vận, Khắc ý, Thiện tính, Thu thủy, Chí lạc, Đạt sinh, Sơn mộc, Điền tử phương, Tri bắc du. Tạp thiên  gồm 11 thiên: Canh tang sở, Từ vô quỉ, Tắc dương, Ngoại vật, Ngụ ngôn, Nhượng vương, Đạo chích, Thuyết kiếm, Ngư phủ, Liệt ngự khấu, Thiên hạ.\r\n\r\nĐối với nhiều độc giả, đây có thể là một tác phẩm khá trừu tượng về lý lẽ và nội dung. Nên trong cuốn sách đã bao gồm phần nguyên bản bằng chữ Hán, phần phiên âm, phần dịch nghĩa và lời bình của tác giả..', 'https://docsach24.com/filemanager/data-images/triet-hoc/nam-hoa-kinh.jpg', 13),
(16, 'a016', 'Anh Macar hay hoài nghi', 'Andrei Platonov', 'Truyện Ngắn - Ngôn Tình', '“Anh Macar Hay Hoài Nghi” là một câu chuyện ngắn của tác giả Andrei Platonov. Đây là một tác phẩm mang bản chất của anh mugic Nga Macar, phê phán tệ quan liêu giấy tờ, coi thường trí tuệ quần chúng bằng lời kể dí dỏm, nhẹ nhàng, sinh động, hấp dẫn và kín đáo. \r\n\r\nCâu chuyện kể về những sự việc xoay quanh những cuộc đời của anh chàng nông dân chất phác có tên là Macar. Marca cũng như bao nhiêu nông dân khác trong làng, anh không đam mê công việc đồng áng mà ngày ngày việc đầu tiên trên mà anh vắt trán lên suy nghĩ là hình thức giải trí mới. Như vậy có thể nói Macar mê các trò thủ công mày mò hơn là công việc cày cuốc, và quan tâm trước hết không phải đến cái ăn, mà là các trò vui chơi giải trí, bởi theo kết luận của đồng chí Shumovoi, Macar là cái anh đầu rỗng.\r\n\r\nAnh hứa làm lại một cái xe tự hành thanh thế cho anh đồng chí Shumovoi, người được coi là coi là thông minh nhất làng, anh còn ở giếng cả đêm để lượm đủ sắt làm cho bà vợ một chiếc lò nướng bánh mới,...', 'https://docsach24.com/filemanager/data-images/truyen-ngan-ngon-tinh/Anh-%20Macar-Hay%20-Hoai%20-Nghi%20(1).jpg', 0),
(17, 'a017', 'TỘI ÁC VÀ SỰ TRỪNG PHẠT', 'Fyodor Dostoevsky', 'Tiểu Thuyết Phương Tây', '“Tội ác và sự trừng phạt” là một tác phẩm tiểu thuyết nổi tiếng của một trong những cây bút tiểu thuyết bậc thầy ở Nga, tác giả Fyodor Dostoevsky.\r\nCâu chuyện kể về một cậu sinh viên, bởi vì cuộc sống đã đẩy bản thân cậu đến đường cùng, lối thoát lúc này với cậu là một thứ gì đó quá sa sỉ, vì vậy cậu đã nhẫn tâm ra tay giết chết bà cháu trong tiệm cầm đồ. Tên của chàng trai đó là Raxkônnikốp.\r\n\r\nChắc chắn cuộc sống của chàng trai về sau đó lại càng bi kịch hơn. Rơi vào một trạng thái thảm vô cùng, khủng hoảng tinh thần một cách trầm trọng. Ngày ngày anh đêu phải nghỉ cách che dấu tội lỗi trong quá khứ của mình, nhưng anh chính thay đổi cách nhìn nhận cuộc sống khi nàng xuất hiện. Cô gái đó có tên là Xônya, cô đến bên Raxkônnikốp bằng tình yêu thương chân thành nhất của một người thiếu nữ, cô quan tâm, chăm sóc và những nỗ lực làm thức tỉnh anh đã thành công.\r\n\r\nAnh quyết định đi thú nhận những tội lỗi xưa của mình, anh nhận ra thà bị giam giữ về thể xác còn hơn là giam giữ bằng tâm hồn.', 'https://docsach24.com/filemanager/data-images/tieu-thuyet-phuong-tay/toi-ac-va-trung-phat.jpg', 21),
(18, 'a018', 'HIỆP KHÍ ĐẠO', 'Koichi Tohei', 'Y Học - Sức Khỏe', 'Sống như thế nào mới gọi là trọn vẹn? Sống như thế nào mới thực sự hạnh phúc? Con người không phải đều có những khởi không đầu giống nhau nhưng kết thúc thúc lại chỉ quay lại với cát bụi vậy sống làm sao để không thấy tiếc nuối quãng thời gian cả một đời người.\r\n\r\n“Hiệp khí đạo” là tác phẩm phù hợp nhất để dẫn dắt chúng ta thực hiện ước muốn trên, tác phẩm do tác giả Koichi Tohei sáng tác nhằm tạo một định hướng đúng đắn hững dẫn con người cách phát triển bản thân ở đây đặc biệt là phát triển đội tâm cá nhân sao cho mở được cánh cửa mà ít ai có thể mở được.\r\n\r\nĐó là cách vận dụng khí, một sức mạnh vô cùng cẫn thiết để phát triền con người. Cuốn sách này là một nổ lực của tác giả để thỏa mãn những đòi hỏi mà tác giả đã nhận được từ các nước trên thế giới yêu cầu giải nghĩa kỹ lưỡng hơn về KHÍ và cống hiến cách áp dụng những phương pháp huấn luyện cùng những nguyên lý Hiệp Khí Đạo trong đời sống hằng ngày. Không gì làm tác giả sung sướng hơn là nếu cuốn sách này có thể thỏa mãn những yêu cầu đó và được dùng làm tài liệu cho bạn đọc nào muốn nghiên cứu sâu xa hơn. ', 'https://docsach24.com/filemanager/data-images/y-hoc-suc-khoe/Hiep%20khi%20dao.jpg', 18),
(19, 'a019', 'BÀN TAY ÁNH SÁNG', 'Barbara Ann Brennan', 'Tâm Lý - Kỹ Năng Sống', '“Bàn tay ánh sáng” là một trong những tác phẩm nổi tiếng nhất của tác giả Barbara Ann Brennan.\r\nBạn có tin vào quy luật nhân quả hay không? Bạn có tin rằng có một mối quan hệ mật thiết giữa con người và vũ trụ toàn năng? Cuốn sách này sẽ thực sự đào sâu về những vấn đề đó. Cuốn sách trình bày một nghiên cứu có chiều sâu về hào quang con người và mối quan hệ của nó với quá trình chữa bệnh cả về tâm lý lẫn thể chất. Cuốn sách trình bày một quan điểm toàn diện về cách sống có lợi cho sức khỏe và sinh trưởng. Nó được viết ra cho những người đặc trách bảo vệ sức khỏe, các thầy thuốc nội khoa, các tăng lữ và tất cả những ai tự coi mình là người khao khát có sức khỏe tốt hơn về thể chất, tâm lý và tâm linh.\r\n\r\nCuốn sách là phương pháp chữa trị hoàn toàn khác lạ với những phương pháp cổ truyền vốn có nhưng thực sự đáng tin cậy. Tuy những kiến thức được nói đến khá hàn lâm và trừu tượng nhưng đều có cơ sở đã được chứng minh hoặc được thực hành qua.', 'https://docsach24.com/filemanager/data-images/tam-ly-ky-nang-song/ban-tay-anh-sang.jpg', 20),
(20, 'a020', 'Cửu Âm Giáo', 'Liễu Tàng Dương', 'Kiếm Hiệp - Tiên Hiệp', '“Cửu Âm Giáo” là một bộ truyện kiếm hiệp vô cùng thú vị và hấp dẫn được viết bởi tác giả Liễu Tàng Dương. Nhân vật chính xuyên suốt câu chuyện là Cao Đình Phương, một chàng trai đầy bản lĩnh và khí phách.\r\n\r\nHành trình chiến đấu đầy gian nan của Cao Đình Phương bắt đầu từ Thạch Tháp bảo. Theo như di ngôn của mẹ hắn, Thạch Tháp bảo là một tòa tháp cao lớn, có một màu sẫm tối nổi bật giữa nền trời. Và quả thực, khi đến nơi, Cao Đình Phương đã bị vẻ bề ngoài của tòa tháp làm cho choáng ngợp. Đặc biệt thứ màu sắc đen tối đã khiến cho Thạch Tháp bảo vừa mang vẻ rùng rợn vừa có chút bí ẩn, ma quái.\r\n\r\nCao Đình Phương khi ấy đang bị thương ở chân. Nhưng nghe nói Thạch Tháp bảo đang tuyển gia nhân hầu hạ nên đã quyết định tìm đến đây. Hắn vừa tiến vào, đôi chân khập khiễng vừa run lên. Tuy nhiên, Thạch Tháp không phải là nơi ai muốn vào thì vào. Cao Đình Phương vừa bước vào thì đã có một giọng nói chặn lại. Và dường như, khi nhìn thấy đôi chân khập khiễng của hắn, kẻ lạ mặt kia đã tỏ vẻ coi thường không thương tiếc. Một kẻ bị tàn phế thì làm sao có thể làm gia nhân được.', 'https://docsach24.com/filemanager/data-images/kiem-hiep-tien-hiep/cuu-am-giao.jpg', 0),
(21, 'a021', 'Hành trình của sói', 'BÙI ANH TẤN', 'Văn Học Việt Nam', '“Hành Trình Của Sói” là một tác phẩm tiêu biểu của tác giả Bùi Anh Tấn viết về vụ án “Năm Cam và đồng bọn”. Đây là một vụ án có thật ở nước ta với quy mô vô cùng lớn và để lại nhiều bài học quý báu không chỉ cho chúng ta mà còn cho ngành công an.\r\n\r\n“Năm Cam và đồng bọn” là một băng nhóm xã hội đen hoạt động vô cùng phức tạp, có liên quan tới nhiều đối tượng, nhiều tỉnh thành phố. Qua vụ án, ta có thể thấy được nhiều vấn đề đáng quan tâm của con người và xã hội. Khi đạo đức của con người xuống cấp trầm trọng và giá trị vật chất được đề cao quá mức, con người dường như không kiểm soát được hành động đúng sai của mình nữa. Do đó, để mọi người có thể nhận thức được điều này và rút ra những bài học cho mình, tác giả Bùi Anh Tấn đã quyết định phân tích và tập hợp tư liệu viết thành cuốn sách mang tên “Hành Trình Của Sói”.\r\n\r\nXuyên suốt cuộc đời của mình, tác giả Bùi Anh Tấn có nhiều gắn bó với ngành công an và ông cũng có nhiều những tác phẩm viết về ngành với những thành công nhất định. Trong đó, tác phẩm “Hành Trình Của Sói” với vụ án “Năm Cam và đồng bọn” đã trở thành tiêu biểu.', 'https://docsach24.com/filemanager/data-images/van-hoc-viet-nam/hanh-trinh-cua-soi.jpg', 4);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `user`
--

CREATE TABLE `user` (
  `id` int(255) NOT NULL,
  `username` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(100) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `user`
--

INSERT INTO `user` (`id`, `username`, `email`, `password`) VALUES
(1, 'danh', 'danh@gmail.com', '123'),
(37, 'asdasdasdas', 'danh@gmail.com', '123'),
(38, 'asdasdasdas', 'danh@gmail.com', '123'),
(39, 'asdasdasdas', 'danh@gmail.com', '123'),
(40, 'cdanh', 'danh@gmail.com', '123');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `sach`
--
ALTER TABLE `sach`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `sach`
--
ALTER TABLE `sach`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- AUTO_INCREMENT cho bảng `user`
--
ALTER TABLE `user`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
